import { useCallback, useEffect, useMemo, useState } from 'react';
export default function Flashcards({ cards, onViewed }) {
  const [order, setOrder] = useState(() => cards.map((_, i) => i)); const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false);
  const current = useMemo(() => cards[order[index]], [cards, order, index]);
  const move = useCallback((n) => { setIndex(i => Math.min(order.length - 1, Math.max(0, i + n))); setFlipped(false); }, [order.length]);
  useEffect(() => { onViewed(order[index]); }, [index, order, onViewed]);
  useEffect(() => { const key = e => { if (e.target.tagName === 'TEXTAREA') return; if (e.key === 'ArrowLeft') move(-1); if (e.key === 'ArrowRight') move(1); if (e.key === ' ') { e.preventDefault(); setFlipped(x => !x); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [move]);
  const shuffle = () => { setOrder(o => [...o].sort(() => Math.random() - .5)); setIndex(0); setFlipped(false); };
  return <section className="card p-5 sm:p-7"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="section-title">Flashcards</h2><p className="muted">Use ← → to move and Space to flip.</p></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-sm font-bold text-indigo-700 dark:bg-indigo-950 dark:text-indigo-200">{index + 1} / {cards.length}</span></div><button aria-label="Flip flashcard" onClick={() => setFlipped(x => !x)} className={'flashcard ' + (flipped ? 'is-flipped' : '')}><span className="face front"><small>QUESTION</small><strong>{current.question}</strong><em>Click or press Space to reveal</em></span><span className="face back"><small>ANSWER</small><strong>{current.answer}</strong><em>Click to see the question</em></span></button><div className="mt-5 flex flex-wrap justify-between gap-3"><button className="secondary" onClick={() => move(-1)} disabled={!index}>← Previous</button><div className="flex gap-2"><button className="secondary" onClick={shuffle}>Shuffle</button><button className="secondary" onClick={() => { setIndex(0); setFlipped(false); }}>Restart</button></div><button className="primary" onClick={() => move(1)} disabled={index === cards.length - 1}>Next →</button></div></section>;
}
